### ISSUE TITLE
Bug in Workouts struct definition

### ISSUE THREAD

**Issue by sonmaximum** [lildude/oura#10]
Hi, I found a bug in the workout.go file - the Workouts struct contains tags in its data property, not workouts.  

There were also a couple improper declarations in the unmarshalling in the tests.

I've submitted a PR to correct them.  Lemme know if you have any questions/issues

**Comment by sonmaximum** [comment]
@lildude Hey, thanks for merging this.  Really sorry for being a nag, but, any way you can push it out in a release?

**Comment by lildude** [comment]
Whoops. Sorry. I completely forgot about making a release. I've just made v0.3.1.
