### ISSUE TITLE
Support Additional V2 endpoints, and discontinuation of Oura API V1

### ISSUE THREAD

**Issue by sonmaximum** [lildude/oura#15]
Hi!  As this is the de facto best and only (that I know of) client for Oura Ring in Golang, I wanted to report that there have been some changes to the API since this project was last updated.

Entries for existing endpoints for DailyActivity, DailyReadiness, DailySleep, Personal Info, Session, Sleep, Tag, and Workouts have now all been assigned an `id` property.

Also, single entries from each of those endpoints (excluding Personal Info) can be accessed individually using that `id` at the endpoint /v2/usercollection/{collection name}/{document_id} (e.g. `https://api.ouraring.com/v2/usercollection/daily_activity/2-5daccc095220cc5493a4e9c2b681ca941e'`)

(I believe the Heart Rate endpoint is unchanged)

Additionally, the following new endpoints have been implemented

- Daily SPO2
- Rest Mode Period
- Ring Configuration
- Sleep Time

There is also an endpoint for creating a webhook subscription, but that may be outside of the scope of this project.

Documentation for all of these are at https://cloud.ouraring.com/v2/docs

Finally, Oura has announced that it is discontinuing its V1 API in Jan 2024, after which it will be unavailable.

Just reporting all of this in case the project maintainer wants to take it into account.

**Comment by lildude** [comment]
Thanks @sonmaximum I've been tracking these updates too, but haven't had the time to implement the changes.

That said, I'm considering archiving this project in favour of using https://github.com/deepmap/oapi-codegen to generate the libraries directly from Oura's OpenAPI spec. When I initially tested it, I found it worked really well and produced code almost identical to what I'm implementing here.

**Comment by sonmaximum** [comment]
Hi @lildude I just wanted to follow up and say that I agree that the code generation from oapi-codgen does seem to work very well.  I ended up refactoring my project to use that (mostly as a result of this conversation).

**Comment by lildude** [comment]
Doing it. Archiving in favour of the gen'd libs.
